version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: petiko
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
